### PR TITLE
Upgrade Luna Streaming image to 2.8.0.1.1.43

### PR DESCRIPTION
**Pull request by nicoloboschi**

### CODE REVIEW

**Comment by nicoloboschi** [comment]
checks failed in this way:
```
Error installing charts: Error identifying charts to process: Must be in a git repository
Error: Error installing charts: Error identifying charts to process: Must be in a git repository
Removing ct container...
Done!
```

I don't think it is related to my pull
@lhotari @michaeljmarshall

**Comment by michaeljmarshall** [comment]
@nicoloboschi - I agree that these failures are unrelated to your PR, I'll take a look.

**Comment by michaeljmarshall** [comment]
@nicoloboschi - I see that the logs indicate `No chart changes detected.`. I didn't think we were requiring chart changes for tests to pass, but that's why these tests failed.

**Comment by michaeljmarshall** [comment]
I fixed the issue in #224.

**Review by michaeljmarshall — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
The tests weren't passing even after closing and reopening. This is a trivial change. Merging now and will verify that the tests on master pass.

**Pull request merged**
