### PR TITLE
fix parse error unclosed action

### PR DESCRIPTION
**Pull request by anxuanzi**
Fix parse error at (pulsar/templates/broker-sts/broker-sts-transactions-metadata.yaml:19): unclosed action

### CODE REVIEW

**Review by michaeljmarshall — COMMENTED** [review]
Thanks for your contribution @anxuanzi! Do you have sample values to reproduce this error? I tried on my machine with different combinations of `.Values.brokerSts.transactionCoordinator.enabled` and `.Values.brokerSts.transactionCoordinator.initialize` (and I removed the `.Release.IsInstall`), but that didn't reproduce the issue. I am using helm version:

```
$ helm version
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}
```

**Comment by michaeljmarshall** [comment]
@anxuanzi - which version of the helm chart are you using? I am using master, which is essentially 3.2.0. I wasn't able to reproduce the error with those values. I tried with a more recent version of helm and that didn't cause any errors either.

```
$ helm version
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

Does it fail for you with a more recent version of helm? Is there documentation that suggests this formatting is wrong? I ask because we use it elsewhere in the template files, so it'd be a larger change to make a complete fix.

**Comment by anxuanzi** [comment]
@michaeljmarshall I'm currently using helm Version:"v3.9.0"

**Comment by michaeljmarshall** [comment]
@anxuanzi - which version of the datastax pulsar helm chart are you using?

**Comment by anxuanzi** [comment]
@michaeljmarshall 
image

**Review by michaeljmarshall — APPROVED** [review]
Sorry for the delay on this @anxuanzi. Thanks for your contribution!

**Pull request merged**
